version: '3.7'
services:
    backend:
        build: ./backend
        ports:
        - "4000:4000"
        volumes:
            - ./backend:/usr/src/app
    frontend:
        build: ./frontend
        ports:
        - "3000:3000"
        volumes:
            - ./frontend/src:/usr/src/app/src
            - ./frontend/public:/usr/src/app/public
            - ./frontend/package.json:/usr/src/app/package.json
            - ./frontend/tsconfig.json:/usr/src/app/tsconfig.json
        # fix webpack dev server issues in the create-react-app with docker
        stdin_open: true